version: '3'

services:

  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 3001:3000
    networks:
      - social
networks:
    social:
      external:
        name: social